Trending page & padding
ChicoState/sound-space pull request #36
Opened 2022-03-05 19:07 UTC by dhelms1

Started to create trending page - currently has tiles for music, videos, and art. Only has album cover, song title, and artist in the list. Will need to make these clickable to play eventually. Also added padding to website pages so that tiles are not going up to the page edges.

2022-03-05 19:37 UTC, snowmang1 requested changes
If you would add comments for future reference by all in the dev team that would be really amazing.

2022-03-05 19:37 UTC, snowmang1 commented on lib/constants/music_list.dart
> +List musicList = [
can you comment what this does explicitly so that Owen and I can learn from this technique of display?

2022-03-05 19:37 UTC, snowmang1 commented on lib/pages/trending/widgets/info_card.dart
> +class InfoCard extends StatelessWidget {
This should probably be changed to a stateful widget so that it will be intractable in the future if I understand you design correctly.

2022-03-05 19:37 UTC, snowmang1 commented on lib/pages/trending/widgets/info_card_small.dart
> +  final VoidCallback onTap;
Can you add comments for where this Calls back to please.

2022-03-05 19:37 UTC, snowmang1 commented on lib/pages/trending/widgets/trending_cards_medium.dart
> +    double _width = MediaQuery.of(context).size.width;
comments? what is this Querying?

2022-03-05 19:37 UTC, snowmang1 commented on lib/widgets/small_screen.dart
> +        child: localNavigator());
what is localNavigator?

2022-03-06 00:30 UTC, SufiyanSyedCSUC approved these changes

2022-03-07 00:09 UTC, closed without merging